services:

  grafana:
    container_name: dev-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    user: '104'

volumes:
  grafana-storage: